import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack/server";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
// @ts-ignore - fontsource has no type declarations for side-effect import
import "@fontsource-variable/inter";
// @ts-ignore - fontsource has no type declarations for side-effect import
import "@fontsource-variable/noto-sans-thai";
// @ts-ignore - fontsource has no type declarations for side-effect import
import "@fontsource/mukta";
import "react-medium-image-zoom/dist/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Netflix API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider defaultTheme="dark">
          <StackProvider app={stackServerApp}>
            <StackTheme>{children}</StackTheme>
          </StackProvider>
        </ThemeProvider>
        <Toaster
          expand
          position="top-right"
          theme="dark"
          toastOptions={{
            style: {
              fontFamily: "'Noto Sans Thai Variable', sans-serif",
              fontSize: "16px",
            },
          }}
        />
      </body>
    </html>
  );
}
