import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack/server";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
// @ts-ignore - fontsource has no type declarations for side-effect import
import "@fontsource-variable/inter";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StackProvider app={stackServerApp}>
          <ThemeProvider defaultTheme="dark">
            <StackTheme>{children}</StackTheme>
          </ThemeProvider>
        </StackProvider>
      </body>
    </html>
  );
}
