import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack/server";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
// @ts-ignore - fontsource has no type declarations for side-effect import
import "@fontsource-variable/inter";
// @ts-ignore - fontsource has no type declarations for side-effect import
import '@fontsource-variable/noto-sans-thai';
import "./globals.css";

export const metadata: Metadata = {
  title: "Netflix API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider defaultTheme="dark">
          <StackProvider app={stackServerApp}>
            <StackTheme>{children}</StackTheme>
          </StackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
